trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: npm install
  
- script: npx webpack-cli --mode production
  displayName: webpack

- publish: $(System.DefaultWorkingDirectory)/dist
  artifact: game