name: Deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      purge-urls:
        required: true
        type: string

jobs:
  build:
    name: Build & deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - run: npx replace-in-files-cli --string='$$build$$' --replacement='${{ env.GITHUB_SHA_SHORT }}' dist/index.html
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 sync dist ${{ secrets.AWS_S3_URI }} --delete
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          PURGE_URLS: ${{ inputs.purge-urls }}
