name: Deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  push:
    branches:
      - main

jobs:
  deploy-2d:
    uses: ./.github/workflows/deploy.yml
    with:
      working-directory: packages/2d
      purge-urls: '["https://atqu.in/games/dungeon","https://atqu.in/games/dungeon/","https://atqu.in/games/dungeon/index.html"]'
    secrets:
      AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_URI: ${{ secrets.AWS_S3_2D_URI }}
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  deploy-3d:
    uses: ./.github/workflows/deploy.yml
    with:
      working-directory: packages/3d
      purge-urls: '["https://atqu.in/games/dungeon3d","https://atqu.in/games/dungeon3d/","https://atqu.in/games/dungeon3d/index.html"]'
    secrets:
      AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_URI: ${{ secrets.AWS_S3_3D_URI }}
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
